<?php
/**
 * Main plugin options array
 * The array is divided by Settings Group
 */

return apply_filters(
	'enjoyinstagram_options',
	[
		'enjoyinstagram_options_default_group' => [
			'enjoyinstagram_code_opt'                      => 'true',
			'enjoyinstagram_images_captured'               => '40',
			'enjoyinstagram_hashtag_popup_moderate'        => '',
			'enjoyinstagram_lightbox_caption_default'      => 'yes',
			'enjoyinstagram_lightbox_style_default'        => 'default',
			'enjoyinstagram_autoreload_default'            => 'false',
			'enjoyinstagram_autoreload_value_default'      => '20000',
			'enjoyinstagram_carousel_moderate_default'     => 'false',
			'enjoyinstagram_carousel_items_number_default' => 4,
			'enjoyinstagram_carousel_link_default'         => 'swipebox',
			'enjoyinstagram_carousel_link_altro_default'   => 'http://instagram.com',
			'enjoyinstagram_carousel_lightbox_caption_default' => 'yes',
			'enjoyinstagram_carousel_lightbox_style_default' => 'default',
			'enjoyinstagram_carousel_navigation_default'   => 'true',
			'enjoyinstagram_carousel_navigation_prev_default' => 'prev',
			'enjoyinstagram_carousel_navigation_next_default' => 'next',
			'enjoyinstagram_carousel_autoplay_default'     => 'true',
			'enjoyinstagram_carousel_autoplay_timeout_default' => '3000',
			'enjoyinstagram_carousel_slidespeed_default'   => '2000',
			'enjoyinstagram_carousel_dots_default'         => 'true',
			'enjoyinstagram_carousel_loop_default'         => 'true',
			'enjoyinstagram_carousel_480px_default'        => '1',
			'enjoyinstagram_carousel_600px_default'        => '3',
			'enjoyinstagram_carousel_768px_default'        => '5',
			'enjoyinstagram_carousel_1024px_default'       => '5',
			'enjoyinstagram_carousel_theme_default'        => 'default',
			'enjoyinstagram_carousel_bordercolor_default'  => '#cccccc',
			'enjoyinstagram_carousel_backcolor_default'    => '#ffffff',
			'enjoyinstagram_carousel_textcolor_default'    => '#333333',
			'enjoyinstagram_carousel_margin_default'       => '0',
			'enjoyinstagram_carousel_autoreload_default'   => 'false',
			'enjoyinstagram_carousel_autoreload_value_default' => '20000',
			'enjoyinstagram_grid_moderate_default'         => 'false',
			'enjoyinstagram_grid_rows_default'             => '2',
			'enjoyinstagram_grid_cols_default'             => '4',
			'enjoyinstagram_grid_step_default'             => 'random',
			'enjoyinstagram_grid_animation_default'        => 'random',
			'enjoyinstagram_grid_animation_speed_default'  => '500',
			'enjoyinstagram_grid_interval_default'         => '3000',
			'enjoyinstagram_grid_onhover_default'          => 'false',
			'enjoyinstagram_grid_rows_480px_default'       => '2',
			'enjoyinstagram_grid_cols_480px_default'       => '4',
			'enjoyinstagram_grid_rows_600px_default'       => '2',
			'enjoyinstagram_grid_cols_600px_default'       => '4',
			'enjoyinstagram_grid_rows_768px_default'       => '2',
			'enjoyinstagram_grid_cols_768px_default'       => '4',
			'enjoyinstagram_grid_rows_1024px_default'      => '2',
			'enjoyinstagram_grid_cols_1024px_default'      => '4',
			'enjoyinstagram_grid_link_default'             => 'swipebox',
			'enjoyinstagram_grid_link_altro_default'       => '#',
			'enjoyinstagram_grid_lightbox_caption_default' => 'yes',
			'enjoyinstagram_grid_lightbox_style_default'   => 'default',
			'enjoyinstagram_grid_margin_default'           => '0',
			'enjoyinstagram_grid_autoreload_default'       => 'false',
			'enjoyinstagram_grid_autoreload_value_default' => '20000',
			'enjoyinstagram_polaroid_moderate_default'     => 'false',
			'enjoyinstagram_polaroid_back_default'         => 'true',
			'enjoyinstagram_polaroid_link_default'         => 'swipebox',
			'enjoyinstagram_polaroid_link_altro_default'   => '#',
			'enjoyinstagram_polaroid_background_default'   => '#ffffff',
			'enjoyinstagram_polaroid_border_width_default' => '1',
			'enjoyinstagram_polaroid_border_color_default' => 'cccccc',
			'enjoyinstagram_polaroid_lightbox_caption_default' => 'yes',
			'enjoyinstagram_polaroid_lightbox_style_default' => 'default',
			'enjoyinstagram_polaroid_autoreload_default'   => 'false',
			'enjoyinstagram_polaroid_autoreload_value_default' => '20000',
			'enjoyinstagram_album_hover_default'           => 'likes',
			'enjoyinstagram_album_link_default'            => 'swipebox',
			'enjoyinstagram_album_link_altro_default'      => 'http://instagram.com',
			'enjoyinstagram_album_random_angle_default'    => 'true',
			'enjoyinstagram_album_delay_default'           => '50',
			'enjoyinstagram_album_margin_default'          => '20',
			'enjoyinstagram_album_animation_in_default'    => '400',
			'enjoyinstagram_album_animation_out_default'   => '400',
			'enjoyinstagram_album_lightbox_caption_default' => 'yes',
			'enjoyinstagram_album_lightbox_style_default'  => 'default',
		],
		'enjoyinstagram_carousel_options'      => [
			'enjoyinstagram_carousel_items_number' => '4',
			'enjoyinstagram_carousel_hashtag'      => '',
			'enjoyinstagram_carousel_user_hashtag' => 'user',
			'enjoyinstagram_carousel_theme'        => 'default',
			'enjoyinstagram_carousel_user'         => '',
		],
		'enjoyinstagram_grid_options'          => [
			'enjoyinstagram_grid_hashtag'      => '',
			'enjoyinstagram_grid_user'         => '',
			'enjoyinstagram_grid_user_hashtag' => 'user',
			'enjoyinstagram_grid_rows'         => '2',
			'enjoyinstagram_grid_cols'         => '5',
		],
	]
);
